[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
csv = "1.3.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.9.0"
image = "0.24"